### ISSUE TITLE
Rotating logs

### ISSUE THREAD

**Issue by staticfloat** [oxinabox/LoggingExtras.jl#31]
[Log rotation](https://en.wikipedia.org/wiki/Log_rotation) is good practice for long-running services, and it seems reasonable to me that `LoggingExtras.jl` should handle it.  There are standard unix tools to do this for you, (e.g. [`logrotate`](https://linux.die.net/man/8/logrotate)) but for those to work, the program needs to be signaled to close and re-open its file handle.

One possibility is that `FileLogger` could take a kwarg to determine whether it should set up a signal handler such that `SIGUSR1` causes it to reopen its log file (as most unix tools with this functionality do).

A better possibility, IMO, is that we have a `RotatingFileLogger` or similar, that does the log rotation automatically.

What do you think?

**Comment by c42f** [comment]
See https://github.com/tanmaykm/LogRoller.jl for some work @tanmaykm has done on this.

**Comment by oxinabox** [comment]
Seems reasonable

**Comment by staticfloat** [comment]
I made an example implementation in #32, since I'm most interested in date-based rolling rather than the size-based rolling that `LogRoller.jl` has.

**Comment by oxinabox** [comment]
closed by either #32 or by  https://github.com/tanmaykm/LogRoller.jl 
depending what you want?
