### ISSUE TITLE
[Request] Reexport Logging?

### ISSUE THREAD

**Issue by kescobo** [oxinabox/LoggingExtras.jl#43]
There's never a time where I do `using LoggingExtras` that I don't also have to do `using Logging`. Would there be any objection to using Reexport (Or, since it's a Stdlib and there [aren't all that many exports](https://github.com/JuliaLang/julia/blob/master/stdlib/Logging/src/Logging.jl#L32-L46), maybe just do it mannually)? I'd be happy to make a PR, but didn't want to be presumptuous.

**Comment by oxinabox** [comment]
yeah, that would be fair.
I think reexporting manually is best.
I would be open to such a PR
